---
# File: _rebalance_test.yml - Example Couchbase Server playbook
#       This playbook fails a node over, rebalances and gathers logs
#

- name: Cluster roles
  hosts: cluster_nodes
  sudo: True
  gather_facts: False
  tasks:

  - name: Create cluster grouping
    group_by: key={{ couchbase_server_node_role }}

- hosts: primary
  sudo: False
  vars_files:
    - ../defaults/main.yml
  vars:
    couchbase_server_primary_node: "{{hostvars[groups['primary'][0]]['ansible_fqdn']}}"
  tasks:

  - name: Create cluster grouping
    group_by: key={{ couchbase_server_node_role }}

  - name: Failover Node CB2
    shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli failover -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} -u {{ couchbase_server_admin }} -p {{ couchbase_server_password }} --server-failover=cb2.local"

  - name: Rebalance cluster
    shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli rebalance -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }}"

- name: Collect info
  hosts: cluster_nodes
  sudo: False
  vars_files:
    - ../defaults/main.yml
  tasks:

  - name: Execute cbcollect_info
    shell: "TMPDIR={{ couchbase_server_tmpdir }} {{ couchbase_server_bin_path }}/cbcollect_info {{ couchbase_server_cbcollect_path }}/{{ ansible_hostname }}.zip"

  - name: Gather logs
    fetch: "src={{ couchbase_server_cbcollect_path }}/{{ ansible_hostname }}.zip dest=var/cbcollect_info/{{ ansible_hostname }}.zip flat=yes"

  - name: Cleanup
    shell: "rm -rf {{ couchbase_server_cbcollect_path }}/{{ ansible_hostname }}.zip"
