---
# File: _rebalance_cluster.yml - Example Couchbase Server playbook
#       This playbook rebalances a cluster
#
- name: Rebalance cluster
  hosts: primary
  sudo: False
  vars_files:
    - ../defaults/main.yml
  vars:
    couchbase_server_primary_node: "{{hostvars[groups['primary'][0]]['ansible_fqdn']}}"
  tasks:

  - name: Create cluster grouping
    group_by: key={{ couchbase_server_node_role }}
  - name: Rebalance cluster
    shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli rebalance -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }}"
